title = "gitleaks config"

[extend]
useDefault = true

[[rules]]
description = "Supabase Service Role Key"
regex = '''eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+'''
id = "supabase-service-role"

[allowlist]
description = "Allowlist for .env.example placeholders"
paths = [".env.example"]
