'use server'

import { createClient } from '@/lib/supabase/server'
import { supabaseAdmin } from '@/lib/supabase/admin'
import { revalidatePath } from 'next/cache'
import { z } from 'zod'
import { checkFeatureAccess } from '@/lib/feature-gate'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type TeamMember = {
  id: string
  email: string
  full_name: string | null
  role: 'owner' | 'admin' | 'agent'
  created_at: string
}

export type InvitationWithInviter = {
  id: string
  email: string
  role: 'owner' | 'admin' | 'agent'
  status: 'pending' | 'accepted' | 'expired' | 'revoked'
  token: string
  expires_at: string
  created_at: string
  inviter_name: string | null
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function getAuthProfile() {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) return null

  const { data: profile } = await supabase
    .from('profiles')
    .select('id, organization_id, role, email')
    .eq('id', user.id)
    .single()

  return profile as {
    id: string
    organization_id: string
    role: 'owner' | 'admin' | 'agent'
    email: string
  } | null
}

// ---------------------------------------------------------------------------
// sendInvitation
// ---------------------------------------------------------------------------

const sendInvitationSchema = z.object({
  email: z.string().email('Email invalide').max(320),
  role: z.enum(['admin', 'agent']),
})

export async function sendInvitation(
  email: string,
  role: 'admin' | 'agent'
): Promise<{ success: boolean; token?: string; error?: string }> {
  const parsed = sendInvitationSchema.safeParse({ email, role })
  if (!parsed.success) {
    return { success: false, error: parsed.error.issues[0]?.message ?? 'Donnees invalides' }
  }

  const profile = await getAuthProfile()
  if (!profile) return { success: false, error: 'Non authentifie' }

  if (profile.role !== 'owner' && profile.role !== 'admin') {
    return { success: false, error: 'Seuls les proprietaires et administrateurs peuvent inviter' }
  }

  const normalizedEmail = parsed.data.email.toLowerCase().trim()

  // Check if already a member
  const { data: existingMember } = await supabaseAdmin
    .from('profiles')
    .select('id')
    .eq('organization_id', profile.organization_id)
    .eq('email', normalizedEmail)
    .single()

  if (existingMember) {
    return { success: false, error: 'Cet utilisateur est deja membre de l\'organisation' }
  }

  // Check if already has a pending invitation
  const { data: existingInvite } = await supabaseAdmin
    .from('invitations')
    .select('id')
    .eq('organization_id', profile.organization_id)
    .eq('email', normalizedEmail)
    .eq('status', 'pending')
    .single()

  if (existingInvite) {
    return { success: false, error: 'Une invitation est deja en attente pour cet email' }
  }

  // Check feature limit (count members + pending invitations)
  const [membersResult, pendingResult] = await Promise.all([
    supabaseAdmin
      .from('profiles')
      .select('*', { count: 'exact', head: true })
      .eq('organization_id', profile.organization_id),
    supabaseAdmin
      .from('invitations')
      .select('*', { count: 'exact', head: true })
      .eq('organization_id', profile.organization_id)
      .eq('status', 'pending'),
  ])

  const totalUsers = (membersResult.count ?? 0) + (pendingResult.count ?? 0)
  const featureCheck = await checkFeatureAccess(profile.organization_id, 'users')

  if (totalUsers >= featureCheck.limit) {
    return {
      success: false,
      error: `Limite d'utilisateurs atteinte (${featureCheck.limit}). Passez au plan Business pour ajouter plus d'utilisateurs.`,
    }
  }

  // Insert invitation (token is auto-generated by DB default)
  const { data: invitation, error } = await supabaseAdmin
    .from('invitations')
    .insert({
      organization_id: profile.organization_id,
      email: normalizedEmail,
      role: parsed.data.role,
      invited_by: profile.id,
    })
    .select('token')
    .single()

  if (error) {
    return { success: false, error: error.message }
  }

  const inv = invitation as { token: string }

  revalidatePath('/dashboard/settings')
  return { success: true, token: inv.token }
}

// ---------------------------------------------------------------------------
// getInvitations
// ---------------------------------------------------------------------------

export async function getInvitations(): Promise<InvitationWithInviter[]> {
  const profile = await getAuthProfile()
  if (!profile) return []

  const { data: invitations } = await supabaseAdmin
    .from('invitations')
    .select('id, email, role, status, token, expires_at, created_at, invited_by')
    .eq('organization_id', profile.organization_id)
    .order('created_at', { ascending: false })

  if (!invitations || invitations.length === 0) return []

  const rawInvitations = invitations as Array<{
    id: string
    email: string
    role: 'owner' | 'admin' | 'agent'
    status: 'pending' | 'accepted' | 'expired' | 'revoked'
    token: string
    expires_at: string
    created_at: string
    invited_by: string
  }>

  // Fetch inviter names
  const inviterIds = [...new Set(rawInvitations.map((i) => i.invited_by))]
  const { data: inviters } = await supabaseAdmin
    .from('profiles')
    .select('id, full_name')
    .in('id', inviterIds)

  const inviterMap = new Map(
    ((inviters ?? []) as Array<{ id: string; full_name: string | null }>).map((p) => [p.id, p.full_name])
  )

  return rawInvitations.map((inv) => ({
    id: inv.id,
    email: inv.email,
    role: inv.role,
    status: inv.status,
    token: inv.token,
    expires_at: inv.expires_at,
    created_at: inv.created_at,
    inviter_name: inviterMap.get(inv.invited_by) ?? null,
  }))
}

// ---------------------------------------------------------------------------
// revokeInvitation
// ---------------------------------------------------------------------------

export async function revokeInvitation(
  invitationId: string
): Promise<{ success: boolean; error?: string }> {
  const profile = await getAuthProfile()
  if (!profile) return { success: false, error: 'Non authentifie' }

  if (profile.role !== 'owner' && profile.role !== 'admin') {
    return { success: false, error: 'Seuls les proprietaires et administrateurs peuvent revoquer' }
  }

  const { error } = await supabaseAdmin
    .from('invitations')
    .update({ status: 'revoked', updated_at: new Date().toISOString() })
    .eq('id', invitationId)
    .eq('organization_id', profile.organization_id)
    .eq('status', 'pending')

  if (error) {
    return { success: false, error: error.message }
  }

  revalidatePath('/dashboard/settings')
  return { success: true }
}

// ---------------------------------------------------------------------------
// acceptInvitation
// ---------------------------------------------------------------------------

export async function acceptInvitation(
  token: string
): Promise<{ success: boolean; error?: string }> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (!user) return { success: false, error: 'Non authentifie' }

  // Fetch invitation by token using admin (bypasses RLS)
  const { data: invitation } = await supabaseAdmin
    .from('invitations')
    .select('id, organization_id, email, role, status, expires_at')
    .eq('token', token)
    .single()

  const inv = invitation as {
    id: string
    organization_id: string
    email: string
    role: 'owner' | 'admin' | 'agent'
    status: string
    expires_at: string
  } | null

  if (!inv) {
    return { success: false, error: 'Invitation introuvable' }
  }

  if (inv.status !== 'pending') {
    return { success: false, error: 'Cette invitation n\'est plus valide' }
  }

  if (new Date(inv.expires_at) < new Date()) {
    // Auto-expire
    await supabaseAdmin
      .from('invitations')
      .update({ status: 'expired', updated_at: new Date().toISOString() })
      .eq('id', inv.id)
    return { success: false, error: 'Cette invitation a expire' }
  }

  // Verify email matches
  if (user.email?.toLowerCase() !== inv.email.toLowerCase()) {
    return {
      success: false,
      error: `Cette invitation est destinee a ${inv.email}. Connectez-vous avec ce compte.`,
    }
  }

  // Update profile: assign to org + role
  const { error: profileError } = await supabaseAdmin
    .from('profiles')
    .update({
      organization_id: inv.organization_id,
      role: inv.role,
      is_onboarded: true,
    })
    .eq('id', user.id)

  if (profileError) {
    return { success: false, error: profileError.message }
  }

  // Mark invitation as accepted
  await supabaseAdmin
    .from('invitations')
    .update({ status: 'accepted', updated_at: new Date().toISOString() })
    .eq('id', inv.id)

  revalidatePath('/dashboard')
  revalidatePath('/dashboard/settings')
  return { success: true }
}

// ---------------------------------------------------------------------------
// getTeamMembers
// ---------------------------------------------------------------------------

export async function getTeamMembers(): Promise<TeamMember[]> {
  const profile = await getAuthProfile()
  if (!profile) return []

  const { data: members } = await supabaseAdmin
    .from('profiles')
    .select('id, email, full_name, role, created_at')
    .eq('organization_id', profile.organization_id)
    .order('created_at', { ascending: true })

  return (members ?? []) as TeamMember[]
}

// ---------------------------------------------------------------------------
// removeTeamMember
// ---------------------------------------------------------------------------

export async function removeTeamMember(
  profileId: string
): Promise<{ success: boolean; error?: string }> {
  const profile = await getAuthProfile()
  if (!profile) return { success: false, error: 'Non authentifie' }

  if (profile.role !== 'owner') {
    return { success: false, error: 'Seul le proprietaire peut retirer des membres' }
  }

  if (profileId === profile.id) {
    return { success: false, error: 'Vous ne pouvez pas vous retirer vous-meme' }
  }

  // Fetch target profile
  const { data: target } = await supabaseAdmin
    .from('profiles')
    .select('role, organization_id')
    .eq('id', profileId)
    .single()

  const t = target as { role: string; organization_id: string } | null

  if (!t || t.organization_id !== profile.organization_id) {
    return { success: false, error: 'Membre introuvable' }
  }

  if (t.role === 'owner') {
    return { success: false, error: 'Impossible de retirer un proprietaire' }
  }

  // Remove from org by setting role to agent and clearing org link
  // We create a new org for this user so they aren't orphaned
  const { error } = await supabaseAdmin
    .from('profiles')
    .delete()
    .eq('id', profileId)

  if (error) {
    return { success: false, error: error.message }
  }

  revalidatePath('/dashboard/settings')
  return { success: true }
}
